name: 蛋咖

on:
  workflow_dispatch:
  schedule:
     - cron: '5 0,2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: dka
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【蛋咖】'
        run: |
          node dka.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 蛋咖

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4,6,8,12 * * *'
  # watch:
  #       types: started
  # repository_dispatch:
  #   types: jd_cash
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      URL: "https://raw.githubusercontent.com/ziye66666/JavaScript/main/Task/QQread.js"
      RUNFILE: "Task/QQread.js"      
      DKAHD: ${{ secrets.DKAHD }}
      DKABODY: ${{ secrets.DKABODY }}
      DKAXSURL: ${{ secrets.DKAXSURL }}
      DKAXSHD: ${{ secrets.DKAXSHD }}
      DKAKKZHD: ${{ secrets.DKAKKZHD }}
      DKAKKZBODY: ${{ secrets.DKAKKZBODY }}
      DKADTHD: ${{ secrets.DKADTHD }}
      DKADTBODY: ${{ secrets.DKADTBODY }}
      DKAQDBODY: ${{ secrets.DKAQDBODY }}
      DKAXWBODY: ${{ secrets.DKAXWBODY }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  repository: Sunert/Scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        #if: env.RLHEADER
        run: |
          npm install
      - name: '运行 【蛋咖】'
        #if: env.RLHEADER
        run: |
          node dka.js
