name: 书旗
on:
  workflow_dispatch:
  schedule:
     - cron: '15,35 4,16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: rxm
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '【书旗】'
        run: |
          cd ~/js   
          node sqxs.js
