name: 阅友小说

on:
  workflow_dispatch:
  schedule:
     - cron: '5 0,2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: yyxs
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【阅友小说】'
        run: |
          node yyxs.js 
        env:        
          yyxsspurl: ${{ secrets.yyxsspurl }}
          yyxssphd: ${{ secrets.yyxssphd }}
	      yyxsspbody: ${{ secrets.yyxxspbody }}
	      yyxsjsurl: ${{ secrets.yyxsjsurl }}
	  yyxsjsbody: ${{ secrets.yyxsjsbody }}
          yyxsscurl: ${{ secrets.yyxsscurl }}
          yyxsschd: ${{ secrets.yyxsschd }}
	  yyxscjurl: ${{ secrets.yyxscjurl }}
          yyxscjhd: ${{ secrets.yyxscjhd }}
          yyxsxxurl: ${{ secrets.yyxsxxurl }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
